repos:
  # Black — verify formatting (do not auto‑rewrite on commit)
  - repo: https://github.com/psf/black
    rev: 25.1.0
    hooks:
      - id: black
        args: ["--check"]

  # Ruff — linter & import sorter
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.12.8
    hooks:
      - id: ruff-check     # the linter
      # args: [--fix]    # optional: auto-fix
      - id: ruff-format    # the formatter
      # args: [--fix]    # optional: auto-fix

  

  # Bandit — security scan (only HIGH severity blocks commits)
  - repo: https://github.com/PyCQA/bandit
    rev: 1.8.6
    hooks:
      - id: bandit
        args: ["-r",".","--severity-level", "high"]
        pass_filenames: false

