repos:
  # Black — verify formatting (do not auto‑rewrite on commit)
  - repo: https://github.com/psf/black
    rev: stable
    hooks:
      - id: black
        args: ["--check"]

  # Ruff — linter & import sorter
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.4.6
    hooks:
      - id: ruff
        args: ["check", "."]

  # Bandit — security scan (only HIGH severity blocks commits)
  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.8
    hooks:
      - id: bandit
        args: ["-r", ".", "--severity-level", "high"]
